### ISSUE TITLE
aliyun-log-logback-appender结合aliyun pandora开发有问题

### ISSUE THREAD

**Issue by cdab1986** [aliyun/aliyun-log-logback-appender#11]
项目启动时，logback.xml文件会被载入两次
第一次正常启动，第二次pandora启动再次读取这个日志配置文件，但第二次就报错了。

17:39:02,380 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:39:02,380 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:39:02,380 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/xuwenjun/IdeaProjects/bc-dispatcher/target/classes/logback.xml]
17:39:02,453 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:39:02,454 |-INFO in ch.qos.logback.core.joran.action.ShutdownHookAction - About to instantiate shutdown hook of type [ch.qos.logback.core.hook.DelayingShutdownHook]
17:39:02,458 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:39:02,467 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [console]
17:39:02,472 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:39:02,508 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.aliyun.openservices.log.logback.LoghubAppender]
17:39:02,509 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [test1]
17:39:02,510 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:39:02,624 |-INFO in ch.qos.logback.core.joran.action.StatusListenerAction - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
17:39:02,626 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:39:02,626 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[ROOT]
17:39:02,627 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [test1] to Logger[ROOT]
17:39:02,627 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:39:02,627 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1d16f93d - Registering current configuration as safe fallback point
2019-02-20 17:39:02,630 [main] INFO         c.a.o.log.producer.inner.IOThread - The IOThread is going to work.
SLF4J: A number (3) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
fail to download http://mvnrepo.alibaba-inc.com/mvn/repository/com/alibaba/citrus/tool/antx-autoconfig/1.2-jdk9/antx-autoconfig-1.2-jdk9.jar to /Users/xuwenjun/.autoconf/autoconf-1.2-jdk9.jar
/Users/xuwenjun/.autoconf/autoconf-1.2-jdk9.jar doesn't exist.
____                 _                   ____              _
|  _ \ __ _ _ __   __| | ___  _ __ __ _  | __ )  ___   ___ | |_
| |_) / _` | '_ \ / _` |/ _ \| '__/ _` | |  _ \ / _ \ / _ \| __|
|  __/ (_| | | | | (_| | (_) | | | (_| | | |_) | (_) | (_) | |_
|_|   \__,_|_| |_|\__,_|\___/|_|  \__,_| |____/ \___/ \___/ \__|
 :: Pandora Boot :: 2.1.7.8

Set log4j.defaultInitOverride to true.
JM.Log:INFO Init JM logger with Log4jLoggerFactory
JM.Log:INFO Log root path: /Users/xuwenjun/logs/
JM.Log:INFO Set pandora log path: /Users/xuwenjun/logs/pandora
JM.Log:INFO Init JM logger with Log4jLoggerFactory
JM.Log:INFO Log root path: /Users/xuwenjun/logs/
JM.Log:INFO Set pandora log path: /Users/xuwenjun/logs/pandora
INFO: spas-client-initializer init
JM.Log:INFO Init JM logger with Slf4jLoggerFactory
JM.Log:INFO Log root path: /Users/xuwenjun/logs/
JM.Log:INFO Set spas log path: /Users/xuwenjun/logs/spas
JM.Log:INFO Init JM logger with Slf4jLoggerFactory success, vipserver-client's ModuleClassLoader
JM.Log:INFO Log root path: /Users/xuwenjun/logs/
JM.Log:INFO Set vipsrv-logs log path: /Users/xuwenjun/logs/vipsrv-logs
17:39:09,935 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:39:09,935 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:39:09,936 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/xuwenjun/IdeaProjects/bc-dispatcher/target/classes/logback.xml]
17:39:10,011 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:39:10,014 |-INFO in ch.qos.logback.core.joran.action.ShutdownHookAction - About to instantiate shutdown hook of type [ch.qos.logback.core.hook.DelayingShutdownHook]
17:39:10,017 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:39:10,031 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [console]
17:39:10,040 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:39:10,100 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.aliyun.openservices.log.logback.LoghubAppender]
17:39:10,104 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [com.aliyun.openservices.log.logback.LoghubAppender]. ch.qos.logback.core.util.IncompatibleClassException
	at ch.qos.logback.core.util.IncompatibleClassException
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:58)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)

**Comment by firedrgon** [comment]
我也遇到了这个问题，请问解决了吗？

**Comment by little-lonely** [comment]
我也遇到了这个问题，先读取了一次jar包中的logback.xml，然后再读取自己指定的logback-spring.xml，直接异常退出了，请问解决了吗
