### ISSUE TITLE
java.lang.NoClassDefFoundError: net/sf/json/JSONException

### ISSUE THREAD

**Issue by wwhworkspace** [aliyun/aliyun-log-logback-appender#15]

**Comment by wwhworkspace** [comment]
2019-05-14 20:11:31,323 [log-producer-io-worker-0] ERROR com.aliyun.openservices.log.producer.inner.IOThread -281   -error -Failed to send data. 
java.lang.NoClassDefFoundError: net/sf/json/JSONException
	at com.aliyun.openservices.log.Client.ParserResponseMessage(Client.java:2506)
	at com.aliyun.openservices.log.Client.SendData(Client.java:2679)
	at com.aliyun.openservices.log.Client.PutLogs(Client.java:775)
	at com.aliyun.openservices.log.producer.inner.IOThread.doSendData(IOThread.java:172)
	at com.aliyun.openservices.log.producer.inner.IOThread.sendData(IOThread.java:126)
	at com.aliyun.openservices.log.producer.inner.IOThread.access$000(IOThread.java:38)
	at com.aliyun.openservices.log.producer.inner.IOThread$1.run(IOThread.java:225)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wwhworkspace** [comment]
@brucewu-fly 你好，我按照文档添加logback.xml和引入依赖之后，启动出现net/sf/json/JSONException找不到，这个是什么问题呀

**Comment by chaolee50** [comment]
你好，可能是工程引入的json-lib包，与appender中引用的冲突了，可以通过mvn dependency:tree看一下
