### ISSUE TITLE
 protobuf-java 最新的版本 3.11.4 ，文档上写的是 2.5.0 , 可以把这两个版本匹配清楚 

### ISSUE THREAD

**Issue by alen19082062** [aliyun/aliyun-log-logback-appender#26]
protobuf-java 最新的版本 3.11.4 ，文档上写的是 2.5.0 ，我试了一下，是可以用的 

<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>3.11.4</version>
</dependency>

======== 以下是文档中的内容 
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>2.5.0</version>
</dependency>
<dependency>
    <groupId>com.aliyun.openservices</groupId>
    <artifactId>aliyun-log-logback-appender</artifactId>
    <version>0.1.15</version>
</dependency>

但改成 aliyun-log-logback-appender 0.1.16 ，运行报错 
希望指定一个准确的配置 

23:37:50,791 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/rachelzhao/dev/local_repo/com/aliyun/openservices/aliyun-log-logback-appender/0.1.16/aliyun-log-logback-appender-0.1.16.jar!/logback.xml]
23:37:50,797 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@271053e1 - URL [jar:file:/Users/rachelzhao/dev/local_repo/com/aliyun/openservices/aliyun-log-logback-appender/0.1.16/aliyun-log-logback-appender-0.1.16.jar!/logback.xml] is not of type file
23:37:50,893 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
23:37:50,895 |-INFO in ch.qos.logback.core.joran.action.ShutdownHookAction - About to instantiate shutdown hook of type [ch.qos.logback.core.hook.DelayingShutdownHook]
23:37:50,902 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.aliyun.openservices.log.logback.LoghubAppender]
23:37:50,914 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [loghubAppender1]
23:37:50,944 |-ERROR in com.aliyun.openservices.log.logback.LoghubAppender[loghubAppender1] - Failed to start LoghubAppender. java.lang.NullPointerException: endpoint cannot be null
	at java.lang.NullPointerException: endpoint cannot be null
	at 	at com.aliyun.openservices.aliyun.log.producer.ProjectConfig.<init>(ProjectConfig.java:48)
	at 	at com.aliyun.openservices.log.logback.LoghubAppender.buildProjectConfig(LoghubAppender.java:93)
	at 	at com.aliyun.openservices.log.logback.LoghubAppender.createProducer(LoghubAppender.java:86)
	at 	at com.aliyun.openservices.log.logback.LoghubAppender.doStart(LoghubAppender.java:81)
	at 	at com.aliyun.openservices.log.logback.LoghubAppender.start(LoghubAppender.java:69)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)

**Comment by ooopSnake** [comment]
我也遇到相同的错误,原因是 #27 

 0.1.16包里面包含了一个 logback.xml 导致启动失败

降级后可以正常使用...
