### ISSUE TITLE
Caused by: java.net.UnknownHostException: ${project-name}.cn-hangzhou.log.aliyuncs.com

### ISSUE THREAD

**Issue by Xlinlin** [aliyun/aliyun-log-logback-appender#33]
com.aliyun.openservices.log.exception.LogException: Web request failed: ${project-name}.cn-hangzhou.log.aliyuncs.com
	at com.aliyun.openservices.log.Client.SendData(Client.java:2144)
	at com.aliyun.openservices.log.Client.PutLogs(Client.java:698)
	at com.aliyun.openservices.aliyun.log.producer.internals.SendProducerBatchTask.sendProducerBatch(SendProducerBatchTask.java:82)
	at com.aliyun.openservices.aliyun.log.producer.internals.SendProducerBatchTask.run(SendProducerBatchTask.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.aliyun.openservices.log.http.client.ClientException: ${project-name}.cn-hangzhou.log.aliyuncs.com
	at com.aliyun.openservices.log.http.utils.ExceptionFactory.createNetworkException(ExceptionFactory.java:19)
	at com.aliyun.openservices.log.http.comm.DefaultServiceClient.sendRequestCore(DefaultServiceClient.java:58)
	at com.aliyun.openservices.log.http.comm.ServiceClient.sendRequestImpl(ServiceClient.java:100)
	at com.aliyun.openservices.log.http.comm.ServiceClient.sendRequest(ServiceClient.java:81)
	at com.aliyun.openservices.log.Client.SendData(Client.java:2127)
	... 9 common frames omitted

**Comment by popitin593** [comment]
使用内网域名，出现同样问题。
{project.name}.cn-hangzhou-intranet.log.aliyuncs.com

`16:09:20,355 |-ERROR in com.****.appender.****[null] - Failed to send log, project=****, logStore=****, topic=, source=, logItem=[com.aliyun.openservices.log.common.LogItem@40aa4fe7], errorCode=RequestError, errorMessage=Web request failed: ****.cn-hangzhou-intranet.log.aliyuncs.com
[ErrorCode]: UnknownHost
[RequestId]: Unknown
`

**Comment by russell7** [comment]
com.aliyun.openservices.log.logback.LoghubAppender 的 project 需要设置值， ${project-name} 看起来没有解析到值。可能是 spring 或其他框架解析有问题。
