### ISSUE TITLE
Failed to start LoghubAppender. java.lang.NullPointerException: endpoint is null

### ISSUE THREAD

**Issue by JellyChenDeveloper** [aliyun/aliyun-log-logback-appender#8]
15:39:20,630 |-ERROR in com.aliyun.openservices.log.logback.LoghubAppender[loghubAppender2] - Failed to start LoghubAppender. java.lang.NullPointerException: endpoint is null
	at java.lang.NullPointerException: endpoint is null
	at 	at com.aliyun.openservices.log.http.utils.CodingUtils.assertParameterNotNull(CodingUtils.java:12)
	at 	at com.aliyun.openservices.log.http.utils.CodingUtils.assertStringNotNullOrEmpty(CodingUtils.java:16)
	at 	at com.aliyun.openservices.log.Client.<init>(Client.java:392)
	at 	at com.aliyun.openservices.log.Client.<init>(Client.java:452)
	at 	at com.aliyun.openservices.log.Client.<init>(Client.java:357)
	at 	at com.aliyun.openservices.log.Client.<init>(Client.java:333)
	at 	at com.aliyun.openservices.log.producer.inner.ClientPool.updateClient(ClientPool.java:34)
	at 	at com.aliyun.openservices.log.producer.LogProducer.setProjectConfig(LogProducer.java:22)
	at 	at com.aliyun.openservices.log.logback.LoghubAppender.doStart(LoghubAppender.java:56)
	at 	at com.aliyun.openservices.log.logback.LoghubAppender.start(LoghubAppender.java:45)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351)
	at 	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:179)
	at 	at cn.com.driven.ec.EcApiApplication.main(EcApiApplication.java:12)
15:39:20,630 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:39:20,633 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:39:20,634 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:39:20,698 |-INFO in ch.qos.logback.core.joran.action.StatusListenerAction - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
15:39:20,702 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to DEBUG
15:39:20,702 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [loghubAppender1] to Logger[ROOT]
15:39:20,703 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [loghubAppender2] to Logger[ROOT]
15:39:20,704 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:39:20,704 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:39:20,705 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4671e53b - Registering current configuration as safe fallback point
15:39:20,711 |-WARN in com.aliyun.openservices.log.logback.LoghubAppender[loghubAppender1] - Attempted to append to non started appender [loghubAppender1].
15:39:20,711 |-WARN in com.aliyun.openservices.log.logback.LoghubAppender[loghubAppender2] - Attempted to append to non started appender [loghubAppender2].
15:39:20.710 [main] INFO  c.a.o.log.producer.inner.IOThread - The IOThread is going to work.
15:39:20,715 |-WARN in com.aliyun.openservices.log.logback.LoghubAppender[loghubAppender1] - Attempted to append to non started appender [loghubAppender1].
15:39:20,715 |-WARN in com.aliyun.openservices.log.logback.LoghubAppender[loghubAppender2] - Attempted to append to non started appender [loghubAppender2].
15:39:20.715 [main] INFO  c.a.o.log.producer.inner.IOThread - The IOThread is going to work.
SLF4J: A number (7) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay

**Comment by brucewu-fly** [comment]
@JellyChenDeveloper, please verify your `logback.xml` and check whether the parameter `endpoint` is NULL. 
The field `endpoint` is required when you use `aliyun-log-logback-appender`.
```
<appender name="aliyun" class="com.aliyun.openservices.log.logback.LoghubAppender">
    <!-- Required parameters -->
    <!-- Configure account and network  -->
    <endpoint>your project endpoint</endpoint>
    <accessKeyId>your accesskey id</accessKeyId>
    <accessKey>your accesskey</accessKey>

    <!-- Configure sls -->
    <projectName>your project</projectName>
    <logstore>your logstore</logstore>
    <!-- Required parameters(end) -->
  </appender>
```

**Comment by HitomiXz** [comment]
我好像也是报这个endpoint is null 的错，但是<endpoint>your project endpoint</endpoint>是有配置的
比如华东1这样配置是否有错？
        <endpoint>cn-hangzhou.log.aliyuncs.com</endpoint>

**Comment by HitomiXz** [comment]
我也报这个错，这个参数已经配置了的
有没有一个带endpoint的实例看一下

**Comment by brucewu-fly** [comment]
确认`pom.xml`中的依赖
```
<dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.aliyun.openservices</groupId>
            <artifactId>aliyun-log-logback-appender</artifactId>
            <version>0.1.5</version>
        </dependency>
```

在resource目录下添加logback配置文件`logback.xml`。
内容如下：
```
<configuration>
    <!--为了防止进程退出时，内存中的数据丢失，请加上此选项-->
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>

    <appender name="aliyun" class="com.aliyun.openservices.log.logback.LoghubAppender">
        <!--必选项-->
        <!-- 账号及网络配置 -->
        <endpoint>cn-beijing.log.aliyuncs.com</endpoint>
        <accessKeyId>accessKeyId</accessKeyId>
        <accessKey>accessKey</accessKey>

        <!-- sls 项目配置 -->
        <projectName>project</projectName>
        <logstore>logstore</logstore>
        <!--必选项 (end)-->
    </appender>

    <root>
        <level value="INFO"/>
        <appender-ref ref="aliyun"/>
    </root>
</configuration>
```
LogbackAppenderDemo.java
```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LogbackAppenderDemo {

    private static final Logger LOGGER = LoggerFactory.getLogger(LogbackAppenderDemo.class);

    public static void main(String[] args) {
        LOGGER.trace("Logback trace log");
        LOGGER.debug("Logback debug log");
        LOGGER.info("Logback info log");
        LOGGER.warn("Logback warn log");
        LOGGER.error("Logback error log", new RuntimeException("Runtime Exception"));
    }

}
```

**Comment by aprilfish** [comment]
logback配置文件名建议兼容logback-spring.xml，spring boot可以为它添加一些spring boot特有的配置项

**Comment by brucewu-fly** [comment]
@aprilfish , 您在使用`aliyun-log-logback-appender`时，可以自己创建一个名为`logback-spring.xml`的配置文件，然后再指定应用程序加载它。
